###############################################
#                                             #
# DisableCrafting By ArcheryIsKey/SuperSniper # 
#                                             #
###############################################

# Item ID's Of Items You Want To Block
# Example: [54, 21, 54]

Items: [54]

#The Message That The Player Is Sent When The Item Cannot Be Crafted
CannotCraftMessage: &6You Cannot Craft This Item.